lots of stuff

diff --git a/run b/run
--- a/run
+++ b/run
@@ -4,14 +4,38 @@ then
     echo "Usage: $(basename $0) target"
     exit 1
 fi
-if [ -z "${BUILD_CMD}" ]
+
+if [ -z "${CXX}" ]
 then
-    echo "enviroment BUILD_CMD is not set"
+    CXX=$(which clang++ 2>/dev/null)
+    if [ $? -ne 0 ]
+    then
+        CXX=$(which g++ 2>/dev/null)
+    fi
+fi
+
+if [ -z "${CXX}" ]
+then
+    echo ""
+    echo "neither clang++ nor g++ can't be found, please set environment variable CXX"
+    exit 1
+else
+    echo ""
+    echo "CXX=${CXX}"
+fi
+
+if ! [ -x ${CXX} ]
+then
+    echo ""
+    echo "${CXX} doesn't exist or isn't exectable"
     exit 1
 fi
+
 echo ""
-echo "build $1 and run test cases..."
+echo "build target $1 and run test cases..."
 echo ""
-COMMAND="${BUILD_CMD} -g utils.cxx $1.cxx $1_test.cxx -o test"
+COMMAND="${CXX} -std=c++11 -g utils.cxx $1.cxx $1_test.cxx -o test"
 echo ${COMMAND}
+echo ""
 ${COMMAND} && ./test && rm test
+echo ""
